# Generated by Django 4.1.7 on 2023-03-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=100, unique=True)),
                ('writer', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'book',
                'managed': True,
            },
        ),
    ]
